# Generated by Django 5.2 on 2025-04-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengiriman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananPengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ekspedisipengiriman',
            name='layanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengiriman.layananpengiriman'),
        ),
    ]
