# Generated by Django 5.2 on 2025-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengiriman', '0002_layananpengiriman_alter_ekspedisipengiriman_layanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananpengiriman',
            name='ongkos_kirim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
