# Generated by Django 5.2 on 2025-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengiriman', '0003_layananpengiriman_ongkos_kirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekspedisipengiriman',
            name='total_biaya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
